### PR TITLE
Change link generation to absolute URL

### PR DESCRIPTION
**Pull request by olforestman**

### CODE REVIEW

**Comment by dabjoern** [comment]
The problem is that as soon as you're on a subpage (not home/ root) then the link looks like http://www.latest.dev.t3o.typo3.org/about/index.php?id=787&type=1364118054. So the link has to start from document root.

What's you proposal?

**Comment by kaystrobach** [comment]
afaik there was a core method, which returns the current document root.

In your case it will be ```/``` in someones other case it might be ```helloworld/typo3test/````

**Comment by dabjoern** [comment]
The link is generated in JS. Therefore we have no core methods. That would mean to have some inline JS or something like that which sets the "absRefPrefix". So what to do?

**Comment by kaystrobach** [comment]
there is a settings array, which is passed to the frontend, we could add the base uri there

**Comment by dabjoern** [comment]
Could you point me to the source or give me a short hint how to achieve this? So you're saying it's just a setting.

**Comment by kaystrobach** [comment]
sure, here is the controller:

* https://github.com/kaystrobach/TYPO3.voice/pull/8#issuecomment-122638576

**Comment by kaystrobach** [comment]
have you tried to set a base uri in the html? this should also fix it without modifications ...

**Pull request merged**
